name: Rebuild pages

on:
  schedule:
  - cron:  '0 3 * * *' # Runs every day at 3am

jobs:
  refresh:

    runs-on: ubuntu-latest

    steps:
    - name: Trigger pages rebuild
      run: |
        curl --fail --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/pages/builds \
          --header "Authorization: Bearer $GITHUB_TOKEN"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
