name: Rebuild pages

on:
  schedule:
  - cron: 0 2 * * 0-6

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Trigger pages build and deployment
      run: curl -u yourname:${GITHUB_TOKEN} -X POST https://api.github.com/repos/G00fY2/g00fy2.github.io/pages/builds -H "Accept: application/vnd.github.mister-fantastic-preview+json"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
